name: Run R Script and Save Artifact

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ghcr.io/r-wasm/webr:main
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up R
        uses: r-lib/actions/setup-r@v2

      - name: Run R script to create the repo
        run: Rscript create_webR_repo.R
          

      - name: Upload wasm image to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: "vfs/*"
          tag: ${{ github.ref }}
          file_glob: true
          overwrite: true