name: Run R Script and Save Artifact

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      # Build the local R package and structure the CRAN repository
      - name: Build Wasm R packages
        uses: r-wasm/actions/build-rwasm@v2
        with:
          packages: |
            Resourcecode-project/r-resourcecodedata
            resourcecode
            ggplot2
            openair
            hexbin
          repo-path: "_site"
          

      - name: Upload wasm image to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: "vfs/*"
          tag: ${{ github.ref }}
          file_glob: true
          overwrite: true
        permissions:
          # For publishing artifact files to the release
          contents: write
          # To download GitHub Packages within action
          repository-projects: read